[project]
name = "loop-node"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.governance]
path = "contracts/governance.clar"
depends_on = []

[contracts.node-data-verification]
path = "contracts/node-data-verification.clar"
depends_on = []

[contracts.node-registry]
path = "contracts/node-registry.clar"
depends_on = []

[contracts.node-rewards]
path = "contracts/node-rewards.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
